export const SHIP_FILTER_IDS = {
  AIS: 'ais',
  LIGHT: 'light',
  DARK: 'dark',
  UNATTRIBUTED: 'unattributed',
  SPOOFING: 'spoofing',
  STS: 'sts',
  STS_AIS: 'sts-ais',
  SIMILAR_SHIPS: 'similar-ships',
}

export const SHIP_FILTER_DEFAULTS = {
  [SHIP_FILTER_IDS.AIS]: true,
  [SHIP_FILTER_IDS.LIGHT]: true,
  [SHIP_FILTER_IDS.DARK]: true,
  [SHIP_FILTER_IDS.UNATTRIBUTED]: true,
  [SHIP_FILTER_IDS.SPOOFING]: true,
  [SHIP_FILTER_IDS.STS]: true,
  [SHIP_FILTER_IDS.STS_AIS]: true,
  [SHIP_FILTER_IDS.SIMILAR_SHIPS]: true,
}

// Single source of truth that maps UI filter ids to detection.type values.
export const SHIP_FILTER_TO_DETECTION_TYPES = {
  [SHIP_FILTER_IDS.AIS]: [SHIP_FILTER_IDS.AIS],
  [SHIP_FILTER_IDS.LIGHT]: [SHIP_FILTER_IDS.LIGHT],
  [SHIP_FILTER_IDS.DARK]: [SHIP_FILTER_IDS.DARK],
  [SHIP_FILTER_IDS.UNATTRIBUTED]: [SHIP_FILTER_IDS.UNATTRIBUTED],
  [SHIP_FILTER_IDS.SPOOFING]: [SHIP_FILTER_IDS.SPOOFING],
  [SHIP_FILTER_IDS.STS]: [SHIP_FILTER_IDS.STS],
  [SHIP_FILTER_IDS.STS_AIS]: [SHIP_FILTER_IDS.STS_AIS],
}

export const SHIP_FILTERED_TYPE_IDS = Object.keys(SHIP_FILTER_TO_DETECTION_TYPES)
